name: Build and upload artifacts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required
        run: sh _tools/install_required.sh

      - name: Configure (CMake)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install

      - name: Build solution and deb package
        run: cmake --build build -- -j$(nproc) --target package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: logreader.deb
          # ${{ github.run_id }}
          path: logreader-0.0.1-Linux.deb
          retention-days: 7